In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
df=pd.read_csv('/content/email_spam_dataset_6000.csv')
df.head()

  label                                            message
0   ham        Happy birthday Priya! Have a wonderful day.
1   ham     The interview practice session starts at 6 PM.
2   ham           Mom asked you to call when you get free.
3  spam  FREE gift waiting for you! Reply WIN to receiv...
4   ham          Thanks for your help with the assignment.

In [ ]:
df.shape

(6000, 2)

In [ ]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(4118)

In [ ]:
data=df.where((pd.notnull(df)),'')

In [ ]:
data.shape

(6000, 2)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    6000 non-null   object
 1   message  6000 non-null   object
dtypes: object(2)
memory usage: 93.9+ KB

In [ ]:
data.loc[data['label'] == 'spam', 'label',]=0
data.loc[data['label']=='ham', 'label',]=1

In [ ]:
data.head()

  label                                            message
0     1        Happy birthday Priya! Have a wonderful day.
1     1     The interview practice session starts at 6 PM.
2     1           Mom asked you to call when you get free.
3     0  FREE gift waiting for you! Reply WIN to receiv...
4     1          Thanks for your help with the assignment.

In [ ]:
# Separate the feature's and target
X=data['message']
y=data['label']

In [ ]:
print(X)

0             Happy birthday Priya! Have a wonderful day.
1          The interview practice session starts at 6 PM.
2                Mom asked you to call when you get free.
3       FREE gift waiting for you! Reply WIN to receiv...
4               Thanks for your help with the assignment.
                              ...
5995    Your appointment is confirmed for 9 AM. Refere...
5996    Hi Riya, are you coming to class today? Refere...
5997    You have been chosen for a special reward. Cla...
5998    Please check the document I sent yesterday. Re...
5999                  Don't forget to bring your project.
Name: message, Length: 6000, dtype: object

In [ ]:
print(y)

0       1
1       1
2       1
3       0
4       1
       ..
5995    1
5996    1
5997    0
5998    1
5999    1
Name: label, Length: 6000, dtype: object

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(6000,) (4800,) (1200,)

In [ ]:
print(y.shape, y_train.shape , y_test.shape)

(6000,) (4800,) (1200,)

In [ ]:
#Feature Extraction
feature_extraction=TfidfVectorizer(min_df=1, stop_words='english',lowercase=True)

X_train_features=feature_extraction.fit_transform(X_train)
X_test_features=feature_extraction.transform(X_test)

y_train=y_train.astype('int')
y_test=y_test.astype('int')

In [ ]:
print(X_train)

3897             Hi Kiran, are you coming to class today?
5628    Special promotion: You qualify for a FREE head...
1756    Special promotion: You qualify for a FREE gift...
2346             Mom asked you to call when you get free.
2996           Can we reschedule our meeting to tomorrow?
                              ...
3772    The class has been moved to 4 PM. Reference 4304.
5191           Can we reschedule our meeting to tomorrow?
5226            Thanks for your help with the assignment.
5390    FREE gift waiting for you! Reply WIN to receiv...
860            Can we reschedule our meeting to tomorrow?
Name: message, Length: 4800, dtype: object

In [ ]:
print(X_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 22426 stored elements and shape (4800, 1445)>
  Coords	Values
  (0, 971)	0.4598331829962907
  (0, 975)	0.5809646457565925
  (0, 946)	0.4598331829962907
  (0, 941)	0.37945169190723543
  (0, 1431)	0.3091979649361444
  (1, 1423)	0.39366744226267253
  (1, 1006)	0.482501392016555
  (1, 1007)	0.482501392016555
  (1, 965)	0.2586520790208146
  (1, 969)	0.4694828933102749
  (1, 940)	0.30347268940344924
  (2, 1423)	0.3641814068824651
  (2, 1006)	0.44636161618387
  (2, 1007)	0.44636161618387
  (2, 965)	0.23927881231291367
  (2, 940)	0.28074231981726905
  (2, 967)	0.38251253755730136
  (2, 936)	0.43186580847500455
  (3, 965)	0.43008649195328486
  (3, 988)	0.6383672960918804
  (3, 926)	0.6383672960918804
  (4, 1016)	0.6499305350420339
  (4, 986)	0.5407757471501811
  (4, 1432)	0.533996152527468
  (5, 1029)	0.7071067811865476
  :	:
  (4794, 954)	0.33724039066366446
  (4794, 1027)	0.33724039066366446
  (4794, 1444)	0.33724039066366446
  (4794, 290)	0.706382710542353
  (4795, 941)	0.3261940898809543
  (4795, 1001)	0.27275809585367805
  (4795, 989)	0.3811026671807651
  (4795, 1012)	0.23874564877503263
  (4795, 668)	0.7854691013220746
  (4796, 1016)	0.6499305350420339
  (4796, 986)	0.5407757471501811
  (4796, 1432)	0.533996152527468
  (4797, 1428)	0.5773502691896257
  (4797, 970)	0.5773502691896257
  (4797, 927)	0.5773502691896257
  (4798, 965)	0.22955479659177286
  (4798, 967)	0.36696766798532915
  (4798, 1437)	0.42287682436582663
  (4798, 1014)	0.42287682436582663
  (4798, 1440)	0.3771290652354972
  (4798, 1011)	0.36446552015783207
  (4798, 1000)	0.42417951578824226
  (4799, 1016)	0.6499305350420339
  (4799, 986)	0.5407757471501811
  (4799, 1432)	0.533996152527468

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(X_train_features, y_train)

LogisticRegression()

In [ ]:
y_pred=model.predict(X_train_features)
accuracy_on_training_data=accuracy_score(y_train, y_pred)
print('Accuracy on training data:', accuracy_on_training_data)

Accuracy on training data: 1.0

In [ ]:
y_pred_test=model.predict(X_test_features)
accuracy_on_test_data=accuracy_score(y_test, y_pred_test)
print('Accuracy on test data:', accuracy_on_test_data)

Accuracy on test data: 1.0

In [ ]:
input_your_mail=[""]
input_data_features=feature_extraction.transform(input_your_mail)
prediction=model.predict(input_data_features)
print(prediction)

if (prediction[0]==1):
  print('Ham mail')
else:
  print('Spam mail')

[1]
Ham mail